export type ConnectionCard = {
  number: number;
  title: string;
  prompt: string;
};

export const connectionCards: ConnectionCard[] = [
  { number: 1, title: "Emotions Are Not My Enemy", prompt: "What emotion have you been trying to get rid of lately?" },
  { number: 2, title: "Feelings Are Information", prompt: "If your emotions could tell you something important today, what might they be saying?" },
  { number: 3, title: "Emotions Are Like Weather", prompt: "What has the emotional weather been like inside you today? Sunny, cloudy, stormy, calm—or something else?" },
  { number: 4, title: "Feelings Change", prompt: "Can you remember a strong emotion that felt permanent at the time but eventually passed?" },
  { number: 5, title: "No Wrong Emotion", prompt: "Is there an emotion you believe you \u201cshouldn't\u201d feel? Why?" },
  { number: 6, title: "Naming It", prompt: "What emotion are you experiencing right now?" },
  { number: 7, title: "Beyond \u201cFine\u201d", prompt: "If you couldn't answer \u201cfine\u201d or \u201cokay,\u201d how would you describe how you're really doing?" },
  { number: 8, title: "Where Do You Feel It?", prompt: "When you feel a strong emotion, where do you notice it in your body?" },
  { number: 9, title: "What Happened?", prompt: "What happened recently that stirred something inside you?" },
  { number: 10, title: "What Am I Feeling?", prompt: "Think of a recent difficult moment. What emotion was underneath your first reaction?" },
  { number: 11, title: "Primary Emotions", prompt: "What do you think was the first emotion you felt in your last difficult situation?" },
  { number: 12, title: "Secondary Emotions", prompt: "Have you ever felt angry when you were actually hurt, afraid, or sad?" },
  { number: 13, title: "Anger", prompt: "What might your anger be trying to protect or tell you?" },
  { number: 14, title: "Sadness", prompt: "What have you lost—or wished you had—that you might need to grieve?" },
  { number: 15, title: "Fear", prompt: "What is your fear trying to protect you from?" },
  { number: 16, title: "Joy", prompt: "What has brought you genuine joy recently?" },
  { number: 17, title: "Shame", prompt: "When you feel shame, what does it tell you about yourself? And is that message actually true?" },
  { number: 18, title: "Anxiety", prompt: "What does your anxiety predict will happen?" },
  { number: 19, title: "Loneliness", prompt: "What do you most wish someone understood about your loneliness?" },
  { number: 20, title: "Disappointment", prompt: "What expectation wasn't met, and what did that mean to you?" },
  { number: 21, title: "Pause", prompt: "What happens when you simply sit with an emotion instead of immediately trying to fix it?" },
  { number: 22, title: "Get Curious", prompt: "If you approached your strongest emotion with curiosity instead of judgment, what would you ask it?" },
  { number: 23, title: "What Is This About?", prompt: "Is the intensity of what you're feeling entirely about what is happening right now—or is something older being touched?" },
  { number: 24, title: "The Story", prompt: "What story are you telling yourself about what happened?" },
  { number: 25, title: "Is the Story True?", prompt: "What evidence supports the story you're telling yourself? What evidence doesn't?" },
  { number: 26, title: "The Need Beneath It", prompt: "What might you need underneath this emotion?" },
  { number: 27, title: "What Do You Want?", prompt: "What does this emotion make you want to do?" },
  { number: 28, title: "What Do You Need?", prompt: "Is what you want to do the same as what you actually need?" },
  { number: 29, title: "The Body Knows", prompt: "What physical sensations show up when you're emotionally overwhelmed?" },
  { number: 30, title: "The First Time", prompt: "Does this feeling remind you of another time in your life?" },
  { number: 31, title: "Emotions vs. Actions", prompt: "Can you think of an emotion you've felt strongly without acting on it? What helped?" },
  { number: 32, title: "Feelings Aren't Commands", prompt: "What emotion are you experiencing that you don't have to obey?" },
  { number: 33, title: "Anger Without Harm", prompt: "How can you express anger without hurting yourself or someone else?" },
  { number: 34, title: "Sadness Without Shame", prompt: "What would it look like to let yourself be sad without calling yourself weak?" },
  { number: 35, title: "Fear Without Surrender", prompt: "What would it look like to acknowledge your fear without allowing it to make every decision for you?" },
  { number: 36, title: "Vulnerability", prompt: "What's something you find difficult to tell other men?" },
  { number: 37, title: "Being Known", prompt: "What is one part of your story you wish someone would ask you about?" },
  { number: 38, title: "Receiving", prompt: "When someone tries to support you, what makes it difficult to receive their help?" },
  { number: 39, title: "Being Heard", prompt: "What does someone do that makes you feel genuinely listened to?" },
  { number: 40, title: "Safe Men", prompt: "What qualities make another man feel emotionally safe to you?" },
  { number: 41, title: "The Mask", prompt: "What emotion do you most often hide from other people?" },
  { number: 42, title: "\u201cI'm Fine\u201d", prompt: "When you say \u201cI'm fine\u201d but you're not, what are you protecting?" },
  { number: 43, title: "Strength", prompt: "What does emotional strength mean to you?" },
  { number: 44, title: "Cowboys Don't Cry?", prompt: "Where did you learn that men aren't supposed to cry?" },
  { number: 45, title: "Tears", prompt: "What do you think crying says about a man?" },
  { number: 46, title: "Courage", prompt: "What's something emotionally difficult you've faced that you are proud of?" },
  { number: 47, title: "Compassion", prompt: "How would you speak to a friend who was feeling the same thing you're feeling? Would you speak to yourself that way?" },
  { number: 48, title: "One Step", prompt: "What is one small thing you could do today to care for what you're feeling?" },
  { number: 49, title: "What Do You Want Other Men to Know?", prompt: "What have you learned about emotions that you wish you'd learned when you were younger?" },
  { number: 50, title: "Cowboys Don't Cry?", prompt: "Finish this sentence: \u201cMaybe being a strong man doesn't mean I don't cry. Maybe it means\u2026\u201d" },
];
