export type ConnectionCard = {
  number: number;
  title: string;
  prompt: string;
};

export const connectionCards: ConnectionCard[] = [
  { number: 1, title: "Emotions Are Not My Enemy", prompt: "What emotion have you been trying to get rid of lately?" },
  { number: 2, title: "Feelings Are Information", prompt: "If your emotions could tell you something important today, what might they be saying?" },
  { number: 3, title: "Emotions Are Like Weather", prompt: "What has the emotional weather been like inside you today? Sunny, cloudy, stormy, calm—or something else?" },
  { number: 4, title: "Feelings Change", prompt: "Can you remember a strong emotion that felt permanent at the time but eventually passed?" },
  { number: 5, title: "No Wrong Emotion", prompt: "Is there an emotion you believe you \u201cshouldn't\u201d feel? Why?" },
  { number: 6, title: "Naming It", prompt: "What emotion are you experiencing right now?" },
  { number: 7, title: "Beyond \u201cFine\u201d", prompt: "If you couldn't answer \u201cfine\u201d or \u201cokay,\u201d how would you describe how you're really doing?" },
  { number: 8, title: "Where Do You Feel It?", prompt: "When you feel a strong emotion, where do you notice it in your body?" },
  { number: 9, title: "What Happened?", prompt: "What happened recently that stirred something inside you?" },
  { number: 10, title: "What Am I Feeling?", prompt: "Think of a recent difficult moment. What emotion was underneath your first reaction?" },
  { number: 11, title: "Primary Emotions", prompt: "What do you think was the first emotion you felt in your last difficult situation?" },
  { number: 12, title: "Secondary Emotions", prompt: "Have you ever felt angry when you were actually hurt, afraid, or sad?" },
  { number: 13, title: "Anger", prompt: "What might your anger be trying to protect or tell you?" },
  { number: 14, title: "Sadness", prompt: "What have you lost—or wished you had—that you might need to grieve?" },
  { number: 15, title: "Fear", prompt: "What is your fear trying to protect you from?" },
  { number: 16, title: "Joy", prompt: "What has brought you genuine joy recently?" },
  { number: 17, title: "Shame", prompt: "When you feel shame, what does it tell you about yourself? And is that message actually true?" },
  { number: 18, title: "Anxiety", prompt: "What does your anxiety predict will happen?" },
  { number: 19, title: "Loneliness", prompt: "What do you most wish someone understood about your loneliness?" },
  { number: 20, title: "Disappointment", prompt: "What expectation wasn't met, and what did that mean to you?" },
  { number: 21, title: "Pause", prompt: "What happens when you simply sit with an emotion instead of immediately trying to fix it?" },
  { number: 22, title: "Get Curious", prompt: "If you approached your strongest emotion with curiosity instead of judgment, what would you ask it?" },
  { number: 23, title: "What Is This About?", prompt: "Is the intensity of what you're feeling entirely about what is happening right now—or is something older being touched?" },
  { number: 24, title: "The Story", prompt: "What story are you telling yourself about what happened?" },
  { number: 25, title: "Is the Story True?", prompt: "What evidence supports the story you're telling yourself? What evidence doesn't?" },
  { number: 26, title: "The Need Beneath It", prompt: "What might you need underneath this emotion?" },
  { number: 27, title: "What Do You Want?", prompt: "What does this emotion make you want to do?" },
  { number: 28, title: "What Do You Need?", prompt: "Is what you want to do the same as what you actually need?" },
  { number: 29, title: "The Body Knows", prompt: "What physical sensations show up when you're emotionally overwhelmed?" },
  { number: 30, title: "The First Time", prompt: "Does this feeling remind you of another time in your life?" },
  { number: 31, title: "Emotions vs. Actions", prompt: "Can you think of an emotion you've felt strongly without acting on it? What helped?" },
  { number: 32, title: "Feelings Aren't Commands", prompt: "What emotion are you experiencing that you don't have to obey?" },
  { number: 33, title: "Anger Without Harm", prompt: "How can you express anger without hurting yourself or someone else?" },
  { number: 34, title: "Sadness Without Shame", prompt: "What would it look like to let yourself be sad without calling yourself weak?" },
  { number: 35, title: "Fear Without Surrender", prompt: "What would it look like to acknowledge your fear without allowing it to make every decision for you?" },
  { number: 36, title: "Vulnerability", prompt: "What's something you find difficult to tell other men?" },
  { number: 37, title: "Being Known", prompt: "What is one part of your story you wish someone would ask you about?" },
  { number: 38, title: "Receiving", prompt: "When someone tries to support you, what makes it difficult to receive their help?" },
  { number: 39, title: "Being Heard", prompt: "What does someone do that makes you feel genuinely listened to?" },
  { number: 40, title: "Safe Men", prompt: "What qualities make another man feel emotionally safe to you?" },
  { number: 41, title: "The Mask", prompt: "What emotion do you most often hide from other people?" },
  { number: 42, title: "\u201cI'm Fine\u201d", prompt: "When you say \u201cI'm fine\u201d but you're not, what are you protecting?" },
  { number: 43, title: "Strength", prompt: "What does emotional strength mean to you?" },
  { number: 44, title: "Cowboys Don't Cry?", prompt: "Where did you learn that men aren't supposed to cry?" },
  { number: 45, title: "Tears", prompt: "What do you think crying says about a man?" },
  { number: 46, title: "Courage", prompt: "What's something emotionally difficult you've faced that you are proud of?" },
  { number: 47, title: "Compassion", prompt: "How would you speak to a friend who was feeling the same thing you're feeling? Would you speak to yourself that way?" },
  { number: 48, title: "One Step", prompt: "What is one small thing you could do today to care for what you're feeling?" },
  { number: 49, title: "What Do You Want Other Men to Know?", prompt: "What have you learned about emotions that you wish you'd learned when you were younger?" },
  { number: 50, title: "Cowboys Don't Cry?", prompt: "Finish this sentence: \u201cMaybe being a strong man doesn't mean I don't cry. Maybe it means\u2026\u201d" },
  { number: 51, title: "What's Your Emotional Weather?", prompt: "If your emotions were weather today, what would the forecast be?" },
  { number: 52, title: "Name It", prompt: "What's one emotion you've felt today that you haven't put into words yet?" },
  { number: 53, title: "More Than Angry", prompt: "When you get angry, what emotion might be hiding underneath it?" },
  { number: 54, title: "More Than Fine", prompt: "What's one word that describes how you're really doing\u2014not the word you'd normally give someone?" },
  { number: 55, title: "Your Body's Signal", prompt: "What does your body do when you're becoming emotionally overwhelmed?" },
  { number: 56, title: "The First Sign", prompt: "How do you know you're starting to become stressed before you reach breaking point?" },
  { number: 57, title: "The Storm", prompt: "When your emotions feel overwhelming, what helps you ride out the storm?" },
  { number: 58, title: "Wait Before Reacting", prompt: "What helps you create a little space between feeling something and reacting to it?" },
  { number: 59, title: "Feelings Aren't Facts", prompt: "Have you ever felt something very strongly and later discovered that your interpretation wasn't completely accurate?" },
  { number: 60, title: "Feelings Aren't Commands", prompt: "What's an emotion you've learned you can feel without having to act on it?" },
  { number: 61, title: "What's Underneath?", prompt: "Think of a recent reaction that surprised you. What might have been underneath it?" },
  { number: 62, title: "What Happened?", prompt: "When you experience a strong emotion, how easy is it for you to identify what triggered it?" },
  { number: 63, title: "What's the Story?", prompt: "What story does your mind tend to tell you when you feel rejected?" },
  { number: 64, title: "What Does It Mean?", prompt: "When something hurts you, what meaning do you tend to attach to it?" },
  { number: 65, title: "Old Wounds", prompt: "Have you ever reacted strongly to something small because it touched something much older?" },
  { number: 66, title: "The Need", prompt: "What need might be underneath an emotion you're experiencing right now?" },
  { number: 67, title: "Protection", prompt: "What do you think your anger, fear, or withdrawal might be trying to protect you from?" },
  { number: 68, title: "What Do You Want?", prompt: "When you're upset, what do you usually want to do?" },
  { number: 69, title: "What Do You Need?", prompt: "When you're upset, what do you actually need?" },
  { number: 70, title: "Curiosity", prompt: "What would change if you became curious about your emotions instead of judging them?" },
  { number: 71, title: "The Emotion You Hide", prompt: "Which emotion is hardest for you to show other people?" },
  { number: 72, title: "The Emotion You Show", prompt: "Which emotion do people see from you most easily?" },
  { number: 73, title: "The Mask", prompt: "What do you tend to hide behind when you're hurting?" },
  { number: 74, title: "\u201cI'm Fine\u201d", prompt: "What does \u201cI'm fine\u201d sometimes mean when you're actually not fine?" },
  { number: 75, title: "Toughness", prompt: "What did you learn growing up about what a \u201creal man\u201d is allowed to feel?" },
  { number: 76, title: "Crying", prompt: "What did you learn about crying when you were a boy?" },
  { number: 77, title: "Asking for Help", prompt: "How comfortable are you saying, \u201cI need help\u201d?" },
  { number: 78, title: "Being Vulnerable", prompt: "What makes it difficult for men to be vulnerable with one another?" },
  { number: 79, title: "Being Seen", prompt: "What's something you wish other people could see about you without you having to explain it?" },
  { number: 80, title: "Being Known", prompt: "What's one thing about you that very few people really know?" },
  { number: 81, title: "Validation", prompt: "What's the difference between saying \u201cI understand why you feel that way\u201d and saying \u201cI agree with you\u201d?" },
  { number: 82, title: "Being Heard", prompt: "What does someone do that makes you feel genuinely heard?" },
  { number: 83, title: "Listening", prompt: "When someone is struggling, is your first instinct to listen, fix, advise, or encourage?" },
  { number: 84, title: "Fixing", prompt: "Why can it sometimes be difficult simply to sit with another man's pain without trying to fix it?" },
  { number: 85, title: "A Safe Man", prompt: "What makes another man feel emotionally safe to you?" },
  { number: 86, title: "Trust", prompt: "What helps you trust someone enough to open up?" },
  { number: 87, title: "One Step Deeper", prompt: "What's one question you wish your friends would ask you more often?" },
  { number: 88, title: "Showing Up", prompt: "Think of a time another man showed up for you when you needed him. What did he do?" },
  { number: 89, title: "Receiving", prompt: "Which is harder for you: asking for support or receiving it when someone offers?" },
  { number: 90, title: "Offering", prompt: "What's one way you could become a safer man for another man who is struggling?" },
  { number: 91, title: "A Younger You", prompt: "What emotion did you struggle to express when you were a boy?" },
  { number: 92, title: "What He Needed", prompt: "If you could sit beside your younger self during his hardest moment, what would you want him to know?" },
  { number: 93, title: "The Lesson", prompt: "What's something about emotions you wish someone had taught you when you were younger?" },
  { number: 94, title: "The Old Rule", prompt: "What's one rule about emotions you learned growing up that you no longer believe?" },
  { number: 95, title: "Strength", prompt: "Has your understanding of strength changed as you've grown older? How?" },
  { number: 96, title: "Courage", prompt: "What's more courageous: hiding that you're struggling or telling someone you are? Why?" },
  { number: 97, title: "One Thing", prompt: "What's one emotion you'd like to become better at understanding?" },
  { number: 98, title: "One Change", prompt: "What's one small change you could make in how you deal with emotions?" },
  { number: 99, title: "One Conversation", prompt: "Is there something you've been carrying that you might be ready to talk about with someone you trust?" },
  { number: 100, title: "Cowboys Don't Cry", prompt: "What does \u201cCowboys Don't Cry\u201d mean to you now?" },
];

